"""
routers/calendar.py
====================
GET /calendar/team.ics

Merges every team member's ICS file into a single VCALENDAR and returns it
with Content-Type: text/calendar so browsers / calendar apps can subscribe to
or download it directly.

ICS resolution order per member:
  1. backend/ics/<member_id>.ics   (generated by generate_team_ics.py)
  2. backend/<member.ics_path>     (real ICS path stored in DB, e.g. dummy_maya_calendar.ics)
  3. Skip silently if neither exists.

Each VEVENT SUMMARY is prefixed with "[FirstName] " for easy identification.
"""

from __future__ import annotations

from pathlib import Path

import icalendar
from fastapi import APIRouter
from fastapi.responses import Response
from sqlmodel import Session, select

from database import engine
from models import TeamMember

router = APIRouter()

BACKEND_DIR = Path(__file__).parent.parent
ICS_DIR = BACKEND_DIR / "ics"

# Member IDs that have a real ICS file in the DB ics_path field
REAL_ICS_MEMBERS: set[str] = {"mem-012"}


def _resolve_ics_path(member: TeamMember) -> Path | None:
    """Return the best ICS path for a member, or None if not found."""
    # Prefer the generated per-member file
    generated = ICS_DIR / f"{member.id}.ics"
    if generated.exists():
        return generated

    # Fall back to the DB-stored path (relative to backend/)
    if member.ics_path:
        real = BACKEND_DIR / member.ics_path
        if real.exists():
            return real

    return None


def _first_name(name: str) -> str:
    return name.split()[0]


def _merge_calendars(members: list[TeamMember]) -> bytes:
    merged = icalendar.Calendar()
    merged.add("VERSION", "2.0")
    merged.add("PRODID", "-//Vantage//Team Calendar//EN")
    merged.add("X-WR-CALNAME", "Vantage Team Calendar")
    merged.add("CALSCALE", "GREGORIAN")
    merged.add("METHOD", "PUBLISH")

    for member in members:
        path = _resolve_ics_path(member)
        if path is None:
            continue

        try:
            cal = icalendar.Calendar.from_ical(path.read_bytes())
        except Exception:
            continue

        prefix = f"[{_first_name(member.name)}] "
        for component in cal.walk():
            if component.name != "VEVENT":
                continue

            # Clone by rebuilding from the ical string (safest deep-copy approach)
            cloned = icalendar.Event.from_ical(component.to_ical())
            event = icalendar.Event()
            for key, val in cloned.items():
                event.add(key, val)

            # Prefix the summary
            summary = str(event.get("SUMMARY", ""))
            if not summary.startswith(prefix):
                event["SUMMARY"] = icalendar.vText(prefix + summary)

            merged.add_component(event)

    return merged.to_ical()


@router.get("/calendar/team.ics", include_in_schema=True)
def team_calendar():
    """Download a merged ICS file with all team members' schedules."""
    with Session(engine) as db:
        members = db.exec(select(TeamMember)).all()

    ics_bytes = _merge_calendars(list(members))

    return Response(
        content=ics_bytes,
        media_type="text/calendar",
        headers={
            "Content-Disposition": 'attachment; filename="vantage-team.ics"',
            "Cache-Control": "no-cache",
        },
    )
