import { TeamMember, Task } from './types';

const now = new Date();
const threeHoursAgo = new Date(now.getTime() - 3 * 60 * 60 * 1000);

// ── Tasks at risk ──────────────────────────────────────────────────────────────

export const atRiskTasks: Task[] = [
  {
    id: 'task-001',
    title: 'Auth service migration to OAuth 2.0',
    priority: 'P0',
    assigneeId: 'mem-003',
    deadline: new Date(now.getTime() + 26 * 60 * 60 * 1000), // ~26h out
    projectName: 'Platform / Core Auth',
    status: 'at-risk',
    suggestions: [
      {
        memberId: 'mem-007',
        skillMatchPct: 94,
        workloadPct: 29,
        contextReason: 'Suggested because Jordan has OAuth & Node.js expertise and is 71% free today',
      },
      {
        memberId: 'mem-012',
        skillMatchPct: 81,
        workloadPct: 45,
        contextReason: 'Maya built the original auth layer and has 55% capacity available',
      },
      {
        memberId: 'mem-001',
        skillMatchPct: 68,
        workloadPct: 62,
        contextReason: 'Alex has backend security experience and is partially available this sprint',
      },
    ],
  },
  {
    id: 'task-002',
    title: 'Production incident: payment gateway timeout',
    priority: 'P0',
    assigneeId: 'mem-009',
    deadline: new Date(now.getTime() + 8 * 60 * 60 * 1000), // ~8h out (< 48h = red)
    projectName: 'Payments / Gateway',
    status: 'at-risk',
    suggestions: [
      {
        memberId: 'mem-015',
        skillMatchPct: 88,
        workloadPct: 35,
        contextReason: 'Sam has Stripe API experience and their afternoon is clear',
      },
      {
        memberId: 'mem-004',
        skillMatchPct: 76,
        workloadPct: 50,
        contextReason: 'Priya worked on the original gateway integration last quarter',
      },
      {
        memberId: 'mem-019',
        skillMatchPct: 70,
        workloadPct: 40,
        contextReason: 'Chris has incident response experience and is on-call this week',
      },
    ],
  },
  {
    id: 'task-003',
    title: 'Dashboard performance regression fix',
    priority: 'P1',
    assigneeId: 'mem-006',
    deadline: new Date(now.getTime() + 48 * 60 * 60 * 1000), // exactly 48h
    projectName: 'Frontend / Analytics',
    status: 'at-risk',
    suggestions: [
      {
        memberId: 'mem-012',
        skillMatchPct: 91,
        workloadPct: 38,
        contextReason: 'Maya has React profiling expertise and is 62% available today',
      },
      {
        memberId: 'mem-021',
        skillMatchPct: 79,
        workloadPct: 55,
        contextReason: 'Dana has worked on Recharts optimization and has 45% bandwidth',
      },
      {
        memberId: 'mem-002',
        skillMatchPct: 65,
        workloadPct: 70,
        contextReason: 'Lee identified similar regressions on the mobile app last month',
      },
    ],
  },
  {
    id: 'task-004',
    title: 'Design system token migration (Q1 deadline)',
    priority: 'P1',
    assigneeId: 'mem-016',
    deadline: new Date(now.getTime() + 72 * 60 * 60 * 1000),
    projectName: 'Design / System',
    status: 'at-risk',
    suggestions: [
      {
        memberId: 'mem-023',
        skillMatchPct: 96,
        workloadPct: 22,
        contextReason: 'Aria owns the Figma token library and has 78% availability this week',
      },
      {
        memberId: 'mem-011',
        skillMatchPct: 82,
        workloadPct: 48,
        contextReason: 'Felix contributed to the original token spec and is partially free',
      },
      {
        memberId: 'mem-018',
        skillMatchPct: 71,
        workloadPct: 60,
        contextReason: 'Zoe has CSS variable migration experience from the v2 rebrand',
      },
    ],
  },
  {
    id: 'task-005',
    title: 'Q1 OKR report: product metrics compile',
    priority: 'P2',
    assigneeId: 'mem-022',
    deadline: new Date(now.getTime() + 5 * 24 * 60 * 60 * 1000),
    projectName: 'Product / Strategy',
    status: 'at-risk',
    suggestions: [
      {
        memberId: 'mem-014',
        skillMatchPct: 85,
        workloadPct: 30,
        contextReason: 'Nadia owns the metrics dashboard and can pull this in ~2 hours',
      },
      {
        memberId: 'mem-008',
        skillMatchPct: 74,
        workloadPct: 42,
        contextReason: "Evan prepared last quarter's OKR deck and knows the format",
      },
      {
        memberId: 'mem-020',
        skillMatchPct: 60,
        workloadPct: 55,
        contextReason: 'Taylor has data analytics skills and bandwidth mid-week',
      },
    ],
  },
  {
    id: 'task-006',
    title: 'Accessibility audit: WCAG 2.2 compliance',
    priority: 'P2',
    assigneeId: 'mem-017',
    deadline: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000),
    projectName: 'Design / Accessibility',
    status: 'at-risk',
    suggestions: [
      {
        memberId: 'mem-011',
        skillMatchPct: 88,
        workloadPct: 35,
        contextReason: 'Felix is a11y-certified and has 65% availability next week',
      },
      {
        memberId: 'mem-024',
        skillMatchPct: 77,
        workloadPct: 50,
        contextReason: 'Riley completed WCAG 2.1 audit last cycle and knows the tools',
      },
      {
        memberId: 'mem-013',
        skillMatchPct: 62,
        workloadPct: 68,
        contextReason: 'Morgan has screen-reader testing experience from the mobile project',
      },
    ],
  },
];

// ── Team members ───────────────────────────────────────────────────────────────

export const teamMembers: TeamMember[] = [
  {
    id: 'mem-001',
    name: 'Alex Chen',
    role: 'Senior Backend Engineer',
    team: 'Engineering',
    confidenceScore: 82,
    skills: ['Node.js', 'PostgreSQL', 'Security', 'AWS'],
    dataSources: { calendarPct: 90, taskLoadHours: 22, leaveStatus: 'available' },
    currentTasks: [],
    isOOO: false,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 80, tuesday: 75, wednesday: 85, thursday: 70, friday: 90 },
  },
  {
    id: 'mem-002',
    name: 'Lee Park',
    role: 'Mobile Engineer',
    team: 'Engineering',
    confidenceScore: 55,
    skills: ['React Native', 'Swift', 'Kotlin', 'GraphQL'],
    dataSources: { calendarPct: 60, taskLoadHours: 34, leaveStatus: 'partial' },
    currentTasks: [],
    isOOO: false,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 60, tuesday: 40, wednesday: 55, thursday: 65, friday: 50 },
  },
  {
    id: 'mem-003',
    name: 'Rohan Mehta',
    role: 'Staff Engineer',
    team: 'Engineering',
    confidenceScore: 20,
    skills: ['OAuth', 'Microservices', 'Go', 'Kubernetes'],
    dataSources: { calendarPct: 40, taskLoadHours: 45, leaveStatus: 'ooo' },
    currentTasks: [atRiskTasks[0]],
    isOOO: true,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 0, tuesday: 0, wednesday: 0, thursday: 30, friday: 60 },
  },
  {
    id: 'mem-004',
    name: 'Priya Sharma',
    role: 'Payments Engineer',
    team: 'Engineering',
    confidenceScore: 74,
    skills: ['Stripe', 'Payments', 'Python', 'Django'],
    dataSources: { calendarPct: 80, taskLoadHours: 28, leaveStatus: 'available' },
    currentTasks: [],
    isOOO: false,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 70, tuesday: 80, wednesday: 65, thursday: 75, friday: 70 },
  },
  {
    id: 'mem-005',
    name: 'Marcus Webb',
    role: 'DevOps Engineer',
    team: 'Engineering',
    confidenceScore: 91,
    skills: ['Kubernetes', 'Terraform', 'CI/CD', 'Monitoring'],
    dataSources: { calendarPct: 95, taskLoadHours: 18, leaveStatus: 'available' },
    currentTasks: [],
    isOOO: false,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 90, tuesday: 95, wednesday: 88, thursday: 92, friday: 85 },
  },
  {
    id: 'mem-006',
    name: 'Isabella Torres',
    role: 'Frontend Engineer',
    team: 'Engineering',
    confidenceScore: 15,
    skills: ['React', 'Performance', 'TypeScript', 'Webpack'],
    dataSources: { calendarPct: 30, taskLoadHours: 50, leaveStatus: 'ooo' },
    currentTasks: [atRiskTasks[2]],
    isOOO: true,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 0, tuesday: 0, wednesday: 10, thursday: 40, friday: 70 },
  },
  {
    id: 'mem-007',
    name: 'Jordan Kim',
    role: 'Backend Engineer',
    team: 'Engineering',
    confidenceScore: 88,
    skills: ['OAuth', 'Node.js', 'Redis', 'REST APIs'],
    dataSources: { calendarPct: 90, taskLoadHours: 20, leaveStatus: 'available' },
    currentTasks: [],
    isOOO: false,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 85, tuesday: 90, wednesday: 80, thursday: 88, friday: 82 },
  },
  {
    id: 'mem-008',
    name: 'Evan Liu',
    role: 'Product Manager',
    team: 'Product',
    confidenceScore: 67,
    skills: ['OKRs', 'Roadmapping', 'Analytics', 'JIRA'],
    dataSources: { calendarPct: 70, taskLoadHours: 30, leaveStatus: 'available' },
    currentTasks: [],
    isOOO: false,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 65, tuesday: 70, wednesday: 60, thursday: 68, friday: 72 },
  },
  {
    id: 'mem-009',
    name: 'Camille Dubois',
    role: 'Senior Backend Engineer',
    team: 'Engineering',
    confidenceScore: 10,
    skills: ['Payments', 'Java', 'Spring Boot', 'Kafka'],
    dataSources: { calendarPct: 20, taskLoadHours: 55, leaveStatus: 'ooo' },
    currentTasks: [atRiskTasks[1]],
    isOOO: true,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 0, tuesday: 0, wednesday: 0, thursday: 20, friday: 50 },
  },
  {
    id: 'mem-010',
    name: 'Aisha Okafor',
    role: 'UX Researcher',
    team: 'Design',
    confidenceScore: 95,
    skills: ['User Research', 'Figma', 'Usability Testing', 'Surveys'],
    dataSources: { calendarPct: 100, taskLoadHours: 12, leaveStatus: 'available' },
    currentTasks: [],
    isOOO: false,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 95, tuesday: 100, wednesday: 90, thursday: 95, friday: 88 },
  },
  {
    id: 'mem-011',
    name: 'Felix Wagner',
    role: 'UI Designer',
    team: 'Design',
    confidenceScore: 78,
    skills: ['Figma', 'Accessibility', 'Design Systems', 'Prototyping'],
    dataSources: { calendarPct: 85, taskLoadHours: 24, leaveStatus: 'available' },
    currentTasks: [],
    isOOO: false,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 78, tuesday: 82, wednesday: 75, thursday: 80, friday: 70 },
  },
  {
    id: 'mem-012',
    name: 'Maya Patel',
    role: 'Senior Frontend Engineer',
    team: 'Engineering',
    confidenceScore: 92,
    skills: ['React', 'TypeScript', 'Performance', 'Testing'],
    dataSources: { calendarPct: 95, taskLoadHours: 16, leaveStatus: 'available' },
    currentTasks: [],
    isOOO: false,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 90, tuesday: 95, wednesday: 88, thursday: 92, friday: 85 },
  },
  {
    id: 'mem-013',
    name: 'Morgan Blake',
    role: 'QA Engineer',
    team: 'Engineering',
    confidenceScore: 43,
    skills: ['Selenium', 'Cypress', 'Accessibility Testing', 'Test Plans'],
    dataSources: { calendarPct: 50, taskLoadHours: 38, leaveStatus: 'partial' },
    currentTasks: [],
    isOOO: false,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 50, tuesday: 45, wednesday: 55, thursday: 40, friday: 60 },
  },
  {
    id: 'mem-014',
    name: 'Nadia Kowalski',
    role: 'Senior PM',
    team: 'Product',
    confidenceScore: 88,
    skills: ['Metrics', 'Data Analysis', 'OKRs', 'Stakeholder Management'],
    dataSources: { calendarPct: 90, taskLoadHours: 20, leaveStatus: 'available' },
    currentTasks: [],
    isOOO: false,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 88, tuesday: 85, wednesday: 90, thursday: 82, friday: 80 },
  },
  {
    id: 'mem-015',
    name: 'Sam Rivera',
    role: 'Backend Engineer',
    team: 'Engineering',
    confidenceScore: 79,
    skills: ['Stripe', 'Node.js', 'TypeScript', 'REST APIs'],
    dataSources: { calendarPct: 85, taskLoadHours: 22, leaveStatus: 'available' },
    currentTasks: [],
    isOOO: false,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 75, tuesday: 82, wednesday: 78, thursday: 80, friday: 72 },
  },
  {
    id: 'mem-016',
    name: 'Sofia Andersen',
    role: 'Lead Designer',
    team: 'Design',
    confidenceScore: 25,
    skills: ['Design Systems', 'Figma', 'Brand', 'CSS Tokens'],
    dataSources: { calendarPct: 35, taskLoadHours: 48, leaveStatus: 'ooo' },
    currentTasks: [atRiskTasks[3]],
    isOOO: true,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 0, tuesday: 0, wednesday: 20, thursday: 50, friday: 75 },
  },
  {
    id: 'mem-017',
    name: 'Derek Osei',
    role: 'Designer',
    team: 'Design',
    confidenceScore: 35,
    skills: ['WCAG', 'Accessibility', 'UX Writing', 'Figma'],
    dataSources: { calendarPct: 45, taskLoadHours: 40, leaveStatus: 'partial' },
    currentTasks: [atRiskTasks[5]],
    isOOO: false,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 35, tuesday: 40, wednesday: 30, thursday: 45, friday: 50 },
  },
  {
    id: 'mem-018',
    name: 'Zoe Fernandez',
    role: 'UI Designer',
    team: 'Design',
    confidenceScore: 62,
    skills: ['CSS', 'Design Systems', 'Figma', 'Motion Design'],
    dataSources: { calendarPct: 70, taskLoadHours: 28, leaveStatus: 'available' },
    currentTasks: [],
    isOOO: false,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 62, tuesday: 65, wednesday: 58, thursday: 70, friday: 60 },
  },
  {
    id: 'mem-019',
    name: 'Chris Nakamura',
    role: 'Site Reliability Engineer',
    team: 'Engineering',
    confidenceScore: 85,
    skills: ['Incident Response', 'Monitoring', 'Go', 'PagerDuty'],
    dataSources: { calendarPct: 90, taskLoadHours: 18, leaveStatus: 'available' },
    currentTasks: [],
    isOOO: false,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 82, tuesday: 88, wednesday: 85, thursday: 80, friday: 90 },
  },
  {
    id: 'mem-020',
    name: 'Taylor Morgan',
    role: 'Data Analyst',
    team: 'Product',
    confidenceScore: 58,
    skills: ['SQL', 'Python', 'Looker', 'Data Analytics'],
    dataSources: { calendarPct: 65, taskLoadHours: 32, leaveStatus: 'available' },
    currentTasks: [],
    isOOO: false,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 55, tuesday: 62, wednesday: 58, thursday: 60, friday: 65 },
  },
  {
    id: 'mem-021',
    name: 'Dana Ellis',
    role: 'Frontend Engineer',
    team: 'Engineering',
    confidenceScore: 73,
    skills: ['React', 'Recharts', 'D3.js', 'TypeScript'],
    dataSources: { calendarPct: 80, taskLoadHours: 26, leaveStatus: 'available' },
    currentTasks: [],
    isOOO: false,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 72, tuesday: 78, wednesday: 70, thursday: 75, friday: 68 },
  },
  {
    id: 'mem-022',
    name: 'Lucas Petit',
    role: 'Product Manager',
    team: 'Product',
    confidenceScore: 18,
    skills: ['OKRs', 'Product Strategy', 'Metrics', 'Roadmapping'],
    dataSources: { calendarPct: 25, taskLoadHours: 52, leaveStatus: 'ooo' },
    currentTasks: [atRiskTasks[4]],
    isOOO: true,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 0, tuesday: 0, wednesday: 0, thursday: 25, friday: 60 },
  },
  {
    id: 'mem-023',
    name: 'Aria Johnson',
    role: 'Senior Designer',
    team: 'Design',
    confidenceScore: 96,
    skills: ['Figma', 'Design Tokens', 'CSS', 'Component Libraries'],
    dataSources: { calendarPct: 100, taskLoadHours: 10, leaveStatus: 'available' },
    currentTasks: [],
    isOOO: false,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 96, tuesday: 100, wednesday: 92, thursday: 95, friday: 90 },
  },
  {
    id: 'mem-024',
    name: 'Riley Scott',
    role: 'Designer',
    team: 'Design',
    confidenceScore: 70,
    skills: ['WCAG', 'Accessibility', 'Figma', 'User Testing'],
    dataSources: { calendarPct: 75, taskLoadHours: 26, leaveStatus: 'available' },
    currentTasks: [],
    isOOO: false,
    lastSynced: threeHoursAgo,
    weekAvailability: { monday: 70, tuesday: 72, wednesday: 68, thursday: 74, friday: 65 },
  },
];

// ── Derived aggregates ─────────────────────────────────────────────────────────

export const lastSynced = threeHoursAgo;

export const weekChartData = [
  { day: 'Mon', available: 16 },
  { day: 'Tue', available: 18 },
  { day: 'Wed', available: 14 },
  { day: 'Thu', available: 17 },
  { day: 'Fri', available: 19 },
];
